version: '3.9'

services:
  medusa_db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - medusa_db
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d

volumes:
  pg_data:
